language: python
env:
  - USE_CLIENT_SECRET=True
  - USE_CLIENT_SECRET=False
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install -e '.[test]'"
# command to run tests
script: nosetests warrant.tests --nocapture --nologcapture
